cyp1a2_inducers = ["tobacco smoking", "phenytoin", "rifampin", "ritonavir", "teriflunomide", "insuli", "methylcholanthren", "modafini", "nafcilli", "naphthoflavon", "omeprazol", "lansoprazole"]
cyp1a2_inhibitors = ["fluvoxamine", "liquorice", "enoxacin", "ciprofloxacin", "verapamil", "St. John's wort", "methoxsalen", "mexiletine", "oral contraceptives", "acyclovir", "allopurinol", "mexiletine", "cimetidine", "caffeine", "echinacea", "peginterferon", "theophylline", "piperine", "zileuton", "interferon", "mibefradil", "grapefruit juice", "cumin", "turmeric", "isoniazid", "tetrahydropalmatine", "cannabidiol"]
cyp1a2_substrates = ["fluvoxamine", "amitriptyline", "clomipramine", "imipramine", "agomelatine", "duloxetine", "clozapine", "olanzapine", "haloperidol", "caffeine", "naringenin", "naringin", "quercetin", "rutin", "paracetamol", "propranolol", "ramelteon", "alosetron", "clopidogrel", "ropivacaine", "theophylline", "zolmitriptan", "melatonin", "tamoxifen", "erlotinib", "cyclobenzaprine", "estradiol", "mexiletine", "naproxen", "ondansetron", "phenacetin", "riluzole", "tacrine", "tasimelteon", "tizanidine", "verapamil", "warfarin", "zileuton"]
cyp3a4_inducers = ["carbamazepine", "enzalutamide", "apalutamide", "phenytoin", "rifampin", "upadacitinib", "oxcarbazepine", "topiramate", "phenobarbital", "butalbital", "St. John's wort", "bactericidals", "rifampicin", "rifabutin", "efavirenz", "nevirapine", "troglitazone", "glucocorticoids", "modafinil", "capsaicin", "brigatinib", "clobazam", "dabrafenib", "elagolix", "eslicarbazepine", "letermovir", "lorlatinib", "oritavancin", "perampanel", "telotristat"]
cyp3a4_inhibitors = ["boceprevir", "ritonavir", "indinavir", "nelfinavir", "saquinavir", "clarithromycin", "erythromycin", "telithromycin", "ceritinib", "mibefradil", "nefazodone", "ribociclib", "tucatinib", "chloramphenicol", "ketoconazole", "itraconazole", "posaconazole", "voriconazole", "cobicistat", "green tea extract", "grape seed extract", "dillapiole", "apigenin", "amiodarone", "aprepitant", "ciprofloxacin", "conivaptan", "crizotinib", "rutin", "tofisopam", "verapamil", "diltiazem", "fluconazole", "miconazole", "bergamottin", "cyclosporine", "donedarone", "fluvoxamine", "imatinib", "valerian", "berberine", "buprenorphine", "cilostazol", "cimetidine", "fosaprepitant", "lomitapide", "orphenadrine", "omeprazole", "quercetin", "ranitidine", "ranolazine", "tacrolimus", "ticagrelor", "valproic acid", "amlodipine", "azithromycin", "cannabidiol", "dithiocarbamate", "mifepristone", "norfloxacin", "delavirdine", "gestodene", "star fruit", "milk thistle", "niacin", "ginkgo biloba", "sesamin", "piperine", "isoniazid", "serenoa"]
cyp3a4_substrates = ["amitriptyline", "clomipramine", "imipramine", "cyclobenzaprine", "citalopram", "norfluoxetine", "sertraline", "mirtazapine", "nefazodone", "reboxetine", "venlafaxine", "trazodone", "vilazodone", "buspirone", "haloperidol", "aripiprazole", "risperidone", "ziprasidone", "pimozide", "quetiapine", "lurasidone", "cyclosporin", "tacrolimus", "sirolimus", "upadacitinib", "docetaxel", "tamoxifen", "paclitaxel", "cyclophosphamide", "doxorubicin", "erlotinib", "etoposide", "ifosfamide", "teniposide", "vinblastine", "vincristine", "vindesine", "imatinib", "irinotecan", "sorafenib", "sunitinib", "vemurafenib", "temsirolimus", "anastrozole", "gefitinib", "ketoconazole", "itraconazole", "clarithromycin", "erythromycin", "telithromycin", "dapsone", "alfentanil", "buprenorphine", "codeine", "fentanyl", "hydrocodone", "methadone", "levacetylmethadol", "tramadol", "alprazolam", "midazolam", "triazolam", "diazepam", "clonazepam", "zopiclone", "zaleplon", "zolpidem", "donepezil", "atorvastatin", "lovastatin", "simvastatin", "cerivastatin", "diltiazem", "felodipine", "nifedipine", "verapamil", "amlodipine", "lercanidipin", "nitrendipin", "nisoldipin", "amiodarone", "dronedarone", "quinidine", "sildenafil", "tadalafil", "kinins", "steroid sex hormones", "finasteride", "estradiol", "progesterone", "ethinylestradiol", "testosterone", "toremifene", "bicalutamide", "glucocorticoids", "budesonide", "hydrocortisone", "dexamethasone", "fluticasone", "terfenadine", "astemizole", "chlorphenamine", "nevirapine", "delavirdine", "efavirenz", "etravirine", "rilpivirine", "losartan", "irbesartan", "albendazole", "cisapride", "aprepitant", "caffeine", "cocaine", "cilostazol", "dextromethorphan", "domperidone", "eplerenone", "lidocaine", "ondansetron", "propranolol", "salmeterol", "warfarin", "clopidogrel", "omeprazole", "nateglinide", "methoxetamine", "montelukast", "vilaprisan"]

meds = vcat(cyp1a2_inducers, cyp1a2_inhibitors, cyp1a2_substrates, cyp3a4_inducers, cyp3a4_inhibitors, cyp3a4_substrates)
meds = sort(unique(meds))

for idx in meds
    println("  <tr>")
    println("    <td>$idx</td>")
    idx in cyp1a2_inducers ? println("    <td><font size=\"6\">+</font></td>") : println("    <td><font size=\"5\">-</font></td>")
    idx in cyp1a2_inhibitors ? println("    <td><font size=\"6\">+</font></td>") : println("    <td><font size=\"5\">-</font></td>")
    idx in cyp1a2_substrates ? println("    <td><font size=\"6\">+</font></td>") : println("    <td><font size=\"5\">-</font></td>")
    idx in cyp3a4_inducers ? println("    <td><font size=\"6\">+</font></td>") : println("    <td><font size=\"5\">-</font></td>")
    idx in cyp3a4_inhibitors ? println("    <td><font size=\"6\">+</font></td>") : println("    <td><font size=\"5\">-</font></td>")
    idx in cyp3a4_substrates ? println("    <td><font size=\"6\">+</font></td>") : println("    <td><font size=\"5\">-</font></td>")
    println("  </tr>")
end
